Add CentOS + Fedora Support
Temelio/ansible-role-collectd pull request #3
Opened 2017-12-06 17:12 UTC by con5cience

2017-12-07 22:23 UTC, achaussier commented
Hello, thanks for your work.

I'll check it tomorrow or this week-end.

2017-12-22 17:26 UTC, con5cience commented
I've been using this daily for months and everything works fine. :) Not sure what's up with the tests.

2018-01-06 17:33 UTC, achaussier commented
Hello,

I've set develop branch to be the main target of PR and apply some changes to fix testing and update the role to be validated using Molecule.

I move the target of the PR to develop branch and check the change

2018-01-06 17:45 UTC, achaussier requested changes
Hello,

- can you rebase from develop branch please
- can you fix the following issues
- can you add a molecule test platform to test the new features ?
- can you update Readme and meta files please

Thanks

2018-01-06 17:45 UTC, achaussier commented on tasks/configure.yml
>      src: 'etc/collectd/collectd.conf.j2'
Now, I prefix all roles paths by {{ role_path }}, Can you update this statement please

2018-01-06 17:45 UTC, achaussier commented on tasks/configure.yml
> +    dest: '/{{ collectd_config_directory }}/collectd.conf'
> collectd_config_directory

 value must be the absolute path, same as other variables

2022-06-24 15:16 UTC, closed without merging